name: MasterDeployCI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Rebuild sass
      run: npm rebuild node-sass
    - name: Install Packages
      run: npm install
    - name: Setup environment
      run: |
        echo REACT_APP_MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }} > .env
        echo DB_URL=${{ secrets.DB_URL }} >> .env
    - name: Build project
      run: npm run build
    - name: Run Tests
      run: export CI=true && npm run test -- --coverage
    - name: Deploy to GH pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REACT_APP_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        DB_URL: ${{ secrets.DB_URL }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
