name: Dev_CI_Frontend
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Setup environment
      run: |
        echo REACT_APP_MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }} > .env
        echo DB_URL=${{ secrets.DB_URL }} >> .env
    - name: Build project
      run: npm run build
    - name: Run Tests
      run: npm run test -- --coverage
